openapi: 3.0.0

info:
  title: Design Museum Gent restful API
  description: resftulAPI for linked open data published by Design Museum Gent (Belgium)
  version: 1.0.0
servers:
  - url: https://data.designmuseumgent.be
    description: Main (production server)
paths:
  /exhibitions/billboardseries/: #billboards
    get:
      summary: a list of all billboards
      description: a list of all billboards hosted by Design Museum Gent in JSON-LD
      responses:
        '200': #status code
          description: a JSON array of metadata on billboards organized by 019 and hosted by Design Museum Gent
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    "@type":
                      type: string
                      maxItems: 1

                    # context
                    context:
                      type: object
                      properties:
                        la:
                          type: string
                          maxItems: 1
                        cest:
                          type: string
                          maxItems: 1
                        foaf:
                          type: string
                          maxItems: 1
                        prov:
                          type: string
                          maxItems: 1
                        skos:
                          type: string
                          maxItems: 1
                        cidoc:
                          type: string
                          maxItems: 1
                        label:
                          type: string
                          maxItems: 1
                        inhoud:
                          type: string
                          maxItems: 1
                        "foaf:page":
                          type: object
                          properties:
                            "@type":
                              type: string
                              maxItems: 1
                        "opmerking":
                          type: string
                          maxItems: 1
                        equivalent:
                          type: object
                          properties:
                            "@id":
                              type: string
                              maxItems: 1
                            "@type":
                              type: string
                              maxItems: 1
                        "dcterms:isVersionOf":
                          type: object
                          properties:
                            "@type":
                              type: string
                              maxItems: 1

                     # entiteit.type
                    "Entiteit.type":
                      type: object
                      properties:
                        "@id":
                          type: string
                          maxItems: 1
                        "skos.prefLabel":
                          type: object
                          properties:
                            "@value":
                              type: string
                            "@language":
                              type: string

                    #gebeurtenis.tijd
                    "Gebeurtenis.tijd":
                      type: object
                      properties:
                        "@type":
                          type: string
                          maxItems: 1
                        "@value":
                          type: string

                    #gebeurtenis.plaats
                    "gebeurtenis.plaats":
                      type: object
                      properties:
                        "@type":
                          type: string
                          maxItems: 1
                        equivalent:
                          type: object
                          properties:
                            "@id":
                              type: string
                              maxItems: 1
                            "skos.prefLabel":
                              type: object
                              properties:
                                "@value":
                                  type: string
                                "@language":
                                  type: string

                    #activiteit.gebruiktObject
                    "activiteit.gebruiktObject":
                      type: object
                      properties:
                        "@type":
                          type: string
                          maxItems: 1
                        "MaterieelDing.productie":
                          type: array
                          items:
                            type: object
                            properties:
                              "Activiteit.uitgevoerdDoor":
                                type: array
                                items:
                                  type: object
                                  properties:
                                    "@type":
                                      type: string
                                      maxItems: 1
                                    equivalent:
                                      type: object
                                      properties:
                                        "@id":
                                          type: string
                                          maxItems: 1
                                        "@type":
                                          type: string
                                          maxItems: 1
                                        label:
                                          type: object
                                          properties:
                                            value:
                                              type: string
                                            language:
                                              type: string
                    "MensgemaaktObject.titel":
                      type: string
                    "MensegemaaktObject.beschrijving":
                      type: array
                      items:
                        type: object
                        properties:
                          "@value":
                            type: string
                          "@language":
                            type: string



  /exhibitions: #exhibitions
    get:
      summary: a list of exhibitions
      description: a list of all exhibitions associated with objects from which data has been published by Design Museum Gent
      responses:
        '200': # status code

  /agents: # agent list
    get:
      summary: a list of agents
      description: a list of agents associated with objects from which the data has been published by Design Museum Gent
      responses:
        '200': # status code
  /objects:
    get:
      summary: a list of objects
      description: a list of data describing objects from the collection of Design Museum Gent
      responses:
        '200': #status code
  /texts:
    get:
      summary: a list of texts
      description: a list of texts describing objects and exhibitions related to the collection of Design Museum Gent
      responses:
        '200':